theme: jekyll-theme-minimal
title: Obby chat - Instant messaging app for Obyte
description: Secure end-to-end encryption, cryptocurrency payments, and smart contracts for fun & profit
logo: https://bind.ee/obby-logo.png
google_analytics: UA-39222097-6
