export default {
  WALLET_INIT_START: 'WALLET_INIT_START',
  WALLET_INIT_SUCCESS: 'WALLET_INIT_SUCCESS',
  WALLET_INIT_FAILED: 'WALLET_INIT_FAILED',
  WALLET_BALANCES_FETCH_START: 'WALLET_BALANCES_FETCH_START',
  WALLET_BALANCES_FETCH_SUCCESS: 'WALLET_BALANCES_FETCH_SUCCESS',
  WALLET_BALANCES_FETCH_FAILED: 'WALLET_BALANCES_FETCH_FAILED',
  INITIAL_WALLET_CREATE_START: 'INITIAL_WALLET_CREATE_START',
  INITIAL_WALLET_CREATE_SUCCESS: 'INITIAL_WALLET_CREATE_SUCCESS',
  INITIAL_WALLET_CREATE_FAILED: 'INITIAL_WALLET_CREATE_FAILED',
  EXCHANGE_RATES_SET: 'EXCHANGE_RATES_SET',
  EXCHANGE_RATES_RESET: 'EXCHANGE_RATES_RESET',
};