export default {
  INITIAL_WALLET_CREATE_START: 'INITIAL_WALLET_CREATE_START',
  INITIAL_WALLET_CREATE_SUCCESS: 'INITIAL_WALLET_CREATE_SUCCESS',
  INITIAL_WALLET_CREATE_FAILED: 'INITIAL_WALLET_CREATE_FAILED',
};