require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'Obby Chat' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"

  target 'Obby ChatTests' do
    inherit! :complete
    # Pods for testing
  end

  use_unimodules!
  use_native_modules!
end
target 'Obby Chat-tvOS' do
  # Pods for RNTodo-tvOS
  target 'Obby Chat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
